- pkg/supportability-review-app/edit/sr.cattle.io.reviewbundle.vue
> Fix usage of `Toleration` model for vue3

- pkg/supportability-review-app/edit/sr.cattle.io.reviewbundle.vue
- pkg/supportability-review-app/l10n/en-us.yaml
> Implement a toggle switch to switch between local cluster only and all clusters

- pkg/supportability-review-app/edit/sr.cattle.io.reviewbundle.vue
> Add support for `sonobuoy` namespace

- pkg/supportability-review-app/components/ReportView.vue
- pkg/supportability-review-app/components/Sidebar.vue
> fixed empty eol with trimmed app versions

- pkg/supportability-review-app/components/ReportView.vue
- pkg/supportability-review-app/models/sr.cattle.io.reviewbundle.js
> Use relative path to access APIs

- pkg/supportability-review-app/components/ReportView.vue
> add card sorting based on state and priority

- pkg/supportability-review-app/components/Maincontent.vue
> added hover ver info text to show text to open a new case

- eslint.config.js
- pkg/supportability-review-app/components/InstallView.vue
- pkg/supportability-review-app/components/Maincontent.vue
- pkg/supportability-review-app/components/ReportView.vue
- pkg/supportability-review-app/components/Sidebar.vue
- pkg/supportability-review-app/product.js
> Fix some lint warnings

- pkg/supportability-review-app/components/Maincontent.vue
- pkg/supportability-review-app/components/ReportView.vue
- pkg/supportability-review-app/components/Sidebar.vue
- pkg/supportability-review-app/eslint.config.mjs
- pkg/supportability-review-app/utils/custom-routing.ts
> Fix `lint` warnings

- pkg/supportability-review-app/.prettierrc.json
> Add `quoteProps` to `prettier`

- package.json
- pkg/supportability-review-app/package.json
> Change version number from 105.xxx to 1.n.m

- pkg/supportability-review-app/edit/sr.cattle.io.reviewbundle.vue
> Auto generate token

- pkg/supportability-review-app/package.json
> Add description into Rancer Extension list

- pkg/supportability-review-app/package.json
> Modify app name

- pkg/supportability-review-app/package.json
> Add `kube-version` annotations

- pkg/supportability-review-app/README.md
> Add detail to show in app list

- pkg/supportability-review-app/edit/sr.cattle.io.reviewbundle.vue
- pkg/supportability-review-app/l10n/en-us.yaml
Resolves #55.
[Basic]
[Advanced]
> Show only essential fields by default

- pkg/supportability-review-app/edit/sr.cattle.io.reviewbundle.vue
> Token generation does not work on Rancher 2.8

- pkg/supportability-review-app/models/sr.cattle.io.reviewbundle.js
> Fix path of detailed page

- pkg/supportability-review-app/edit/sr.cattle.io.reviewbundle.vue
> Enable downstream cluster bundle collection only if customer is using Rancher prime

- pkg/supportability-review-app/edit/sr.cattle.io.reviewbundle.vue
Resolves #98.
Now we can collect local cluster only by #97. So we do not need analyzer config.
> Remove analyzer config

- package.json
- yarn.lock
> Upgrade `rancher/shell` 3.0.0 -> 3.0.4

- pkg/supportability-review-app/components/InstallView.vue
- pkg/supportability-review-app/config/types.js
- pkg/supportability-review-app/l10n/en-us.yaml
> Add functionality to register operator repository

- pkg/supportability-review-app/detail/sr.cattle.io.reviewbundle.vue
- pkg/supportability-review-app/edit/sr.cattle.io.reviewbundle.vue
- pkg/supportability-review-app/l10n/en-us.yaml
Resolves #105.
And show the report on Detail page.
> Use Rancher like look and feel for local cluster report

- pkg/supportability-review-app/models/sr.cattle.io.reviewbundle.js
> Transit to detail screen by `View Report`

- pkg/supportability-review-app/edit/sr.cattle.io.reviewbundle.vue
- pkg/supportability-review-app/l10n/en-us.yaml
> Notify community users on the Create screen that Prime users can obtain downstream cluster information

- pkg/supportability-review-app/l10n/en-us.yaml
> corrected dashboard text on operator installation

- pkg/supportability-review-app/l10n/en-us.yaml
> Banner text with Email on report page

- pkg/supportability-review-app/detail/sr.cattle.io.reviewbundle.vue
Resolves #127.
```
ERROR  Failed to compile with 1 error
error  in ./pkg/supportability-review-app/detail/sr.cattle.io.reviewbundle.vue?vue&type=template&id=5639e19e&scoped=true
Module Error (from ./node_modules/vue-loader/lib/loaders/templateLoader.js): (Emitted value instead of an instance of Error)
Errors compiling template:
Component template should contain exactly one root element. If you are using v-if on multiple elements, use v-else-if to chain them instead.
```
> Fix compile error in Rancher 2.8

- pkg/supportability-review-app/detail/sr.cattle.io.reviewbundle.vue
> Remove Cluster State box and move the info under title

- pkg/supportability-review-app/detail/sr.cattle.io.reviewbundle.vue
> Remove checkbox from table

- pkg/supportability-review-app/detail/sr.cattle.io.reviewbundle.vue
> Fix Check Result bar color to regard percentage

- pkg/supportability-review-app/detail/sr.cattle.io.reviewbundle.vue
- pkg/supportability-review-app/l10n/en-us.yaml
> Add All tab

- pkg/supportability-review-app/detail/sr.cattle.io.reviewbundle.vue
> Capitalize the first letter of status

- pkg/supportability-review-app/detail/sr.cattle.io.reviewbundle.vue
> If `local` cluster has multiple EOM/EOL app, UI shows wrong provider

- pkg/supportability-review-app/detail/sr.cattle.io.reviewbundle.vue
> added click on Fail/pass status to open All tabs

- pkg/supportability-review-app/edit/sr.cattle.io.reviewbundle.vue
> fixed bundle name ending with "-"

- pkg/supportability-review-app/models/sr.cattle.io.reviewbundle.js
> Clicking `View Report` on Detail page causes 404 error

- pkg/supportability-review-app/components/InstallView.vue
- pkg/supportability-review-app/config/types.js
- pkg/supportability-review-app/pages/DashboardPage.vue
> Swtich operator repositroy from private to official

- pkg/supportability-review-app/edit/sr.cattle.io.reviewbundle.vue
> App shows warning for community user even in Prime user

- README.md
This reverts commit 3b3b8e20d5e1b0e2a4aa34c684b36c461aa07d04.
> Revert "Remove Container Registry modification once redis image is merged"
